server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: root1234
        driverClassName: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            access-token:
                expiration: 86400000
            refresh-token:
                expiration: 1209600000

converter:
    grpc:
        service:
            host: localhost
            port: 8001
